package p2p_transfer.notification;

public enum NotificationType {
    MONEY_RECEIVED,
    PAYMENT_REQUEST_RECEIVED,
    PAYMENT_REQUEST_PAID,
    PAYMENT_REQUEST_DECLINED,
    PAYMENT_REQUEST_CANCELLED,
    SCHEDULED_TRANSFER_EXECUTED,
    SCHEDULED_TRANSFER_FAILED,
    BUDGET_WARNING,
    BUDGET_EXCEEDED
}
