-- İlk şema: önceki sürümde Hibernate (ddl-auto=update) tarafından üretilen yapının aynısı.
-- IF NOT EXISTS sayesinde mevcut veritabanlarında hiçbir şey değiştirmez; sıfır kurulumda tabloları oluşturur.

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    tckn       VARCHAR(11)  NOT NULL UNIQUE,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT         NOT NULL REFERENCES users (id),
    iban     VARCHAR(255)   NOT NULL UNIQUE,
    balance  NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3)     NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_account_id   BIGINT         NOT NULL REFERENCES accounts (id),
    receiver_account_id BIGINT         NOT NULL REFERENCES accounts (id),
    amount              NUMERIC(19, 2) NOT NULL,
    transaction_date    TIMESTAMP(6)   NOT NULL,
    status              VARCHAR(255)   NOT NULL CHECK (status IN ('SUCCESS', 'PENDING', 'FAILED'))
);
