-- Berq Bank v2: giriş kilidi, çoklu hesap, işlem referansı/kategori/idempotency, kayıtlı alıcılar.

-- ---------- users ----------
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- ---------- accounts ----------
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS name VARCHAR(60) NOT NULL DEFAULT 'Vadesiz Hesap';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Eski arayüz para birimini "TL" olarak gösteriyordu; ISO 4217 koduna normalize et
UPDATE accounts SET currency = 'TRY' WHERE upper(currency) IN ('TL', 'TRL');

-- NOT VALID: geçmişteki hatalı (negatif) kayıtları reddetmez, ama bundan sonraki her yazımı denetler
ALTER TABLE accounts ADD CONSTRAINT chk_accounts_balance_non_negative CHECK (balance >= 0) NOT VALID;

CREATE INDEX IF NOT EXISTS idx_accounts_user ON accounts (user_id);

-- ---------- transactions ----------
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS reference VARCHAR(20);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS currency VARCHAR(3);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS description VARCHAR(140);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS category VARCHAR(32) NOT NULL DEFAULT 'GENERAL';
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(64);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS sender_balance_after NUMERIC(19, 2);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS receiver_balance_after NUMERIC(19, 2);

UPDATE transactions SET reference = 'BQ' || lpad(id::text, 12, '0') WHERE reference IS NULL;
UPDATE transactions t SET currency = a.currency FROM accounts a WHERE t.sender_account_id = a.id AND t.currency IS NULL;

ALTER TABLE transactions ALTER COLUMN reference SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN currency SET NOT NULL;
ALTER TABLE transactions ADD CONSTRAINT uq_transactions_reference UNIQUE (reference);
ALTER TABLE transactions ADD CONSTRAINT chk_transactions_amount_positive CHECK (amount > 0) NOT VALID;

-- Eski kayıtlar JVM yerel saatiyle (Türkiye) yazılmıştı; saat dilimli tipe dönüştür
ALTER TABLE transactions
    ALTER COLUMN transaction_date TYPE TIMESTAMPTZ USING transaction_date AT TIME ZONE 'Europe/Istanbul';

CREATE UNIQUE INDEX IF NOT EXISTS uq_transactions_idempotency
    ON transactions (sender_account_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_transactions_sender_date ON transactions (sender_account_id, transaction_date DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_receiver_date ON transactions (receiver_account_id, transaction_date DESC);

-- ---------- contacts ----------
CREATE TABLE contacts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    account_id BIGINT      NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    nickname   VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_contacts_owner_account UNIQUE (owner_id, account_id)
);
