-- Berq Bank v3: para isteme, bildirimler, düzenli/ileri tarihli transferler, bütçe hedefleri.

-- ---------- para istekleri ----------
CREATE TABLE payment_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id         BIGINT         NOT NULL REFERENCES users (id),
    requester_account_id BIGINT         NOT NULL REFERENCES accounts (id),
    payer_id             BIGINT         NOT NULL REFERENCES users (id),
    amount               NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    currency             VARCHAR(3)     NOT NULL,
    description          VARCHAR(140),
    status               VARCHAR(16)    NOT NULL,
    transaction_id       BIGINT REFERENCES transactions (id),
    created_at           TIMESTAMPTZ    NOT NULL,
    expires_at           TIMESTAMPTZ    NOT NULL,
    responded_at         TIMESTAMPTZ,
    CONSTRAINT chk_payment_requests_parties CHECK (requester_id <> payer_id)
);
CREATE INDEX idx_payment_requests_payer ON payment_requests (payer_id, status, created_at DESC);
CREATE INDEX idx_payment_requests_requester ON payment_requests (requester_id, status, created_at DESC);

-- ---------- düzenli / ileri tarihli transferler ----------
CREATE TABLE scheduled_transfers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT         NOT NULL REFERENCES users (id),
    from_account_id BIGINT         NOT NULL REFERENCES accounts (id),
    to_account_id   BIGINT         NOT NULL REFERENCES accounts (id),
    amount          NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    description     VARCHAR(140),
    category        VARCHAR(32)    NOT NULL,
    frequency       VARCHAR(16)    NOT NULL,
    -- Aylık talimatlarda hedef gün (31 → kısa aylarda ayın son günü); bir sonraki çalışmada geri döner
    day_of_month    INT            NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
    next_run_date   DATE           NOT NULL,
    end_date        DATE,
    status          VARCHAR(16)    NOT NULL,
    last_run_at     TIMESTAMPTZ,
    last_error      VARCHAR(40),
    run_count       INT            NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ    NOT NULL,
    CONSTRAINT chk_scheduled_transfers_accounts CHECK (from_account_id <> to_account_id)
);
CREATE INDEX idx_scheduled_transfers_due ON scheduled_transfers (next_run_date) WHERE status = 'ACTIVE';
CREATE INDEX idx_scheduled_transfers_user ON scheduled_transfers (user_id);

-- ---------- bütçe hedefleri ----------
CREATE TABLE budgets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category      VARCHAR(32)    NOT NULL,
    currency      VARCHAR(3)     NOT NULL,
    monthly_limit NUMERIC(19, 2) NOT NULL CHECK (monthly_limit > 0),
    created_at    TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uq_budgets_user_category_currency UNIQUE (user_id, category, currency)
);

-- ---------- bildirimler ----------
-- Metin saklanmaz: arayüz tür + alanlardan kullanıcının dilinde cümle kurar
CREATE TABLE notifications (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type                  VARCHAR(40)    NOT NULL,
    amount                NUMERIC(19, 2),
    currency              VARCHAR(3),
    counterparty_name     VARCHAR(120),
    category              VARCHAR(32),
    transaction_id        BIGINT REFERENCES transactions (id),
    payment_request_id    BIGINT REFERENCES payment_requests (id),
    scheduled_transfer_id BIGINT REFERENCES scheduled_transfers (id),
    error_code            VARCHAR(40),
    read_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ    NOT NULL
);
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications (user_id) WHERE read_at IS NULL;
