package p2p_transfer;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import p2p_transfer.support.EmbeddedPostgres;

import javax.sql.DataSource;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * v1 uygulaması şemayı Hibernate'in {@code ddl-auto=update} özelliğiyle üretiyordu. Bu test, o dönemden kalma
 * (Flyway geçmişi olmayan, içinde veri bulunan) bir veritabanının v2'ye veri kaybı olmadan yükseltildiğini doğrular.
 */
class LegacyDatabaseMigrationTests {

    private JdbcTemplate jdbc;
    private DataSource dataSource;

    @BeforeEach
    void createLegacyDatabase() {
        String db = "legacy_" + UUID.randomUUID().toString().replace("-", "");
        new JdbcTemplate(EmbeddedPostgres.get().getPostgresDatabase()).execute("CREATE DATABASE " + db);
        dataSource = new DriverManagerDataSource(EmbeddedPostgres.jdbcUrl(db), "postgres", "");
        jdbc = new JdbcTemplate(dataSource);

        // Hibernate 7'nin v1 entity'leri için ürettiği DDL
        jdbc.execute("""
                create table users (id bigint generated by default as identity, email varchar(255) not null unique,
                    first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null,
                    tckn varchar(11) not null unique, primary key (id));
                create table accounts (balance numeric(19,2) not null, currency varchar(3) not null,
                    id bigint generated by default as identity, user_id bigint not null, iban varchar(255) not null unique,
                    primary key (id));
                create table transactions (amount numeric(19,2) not null, id bigint generated by default as identity,
                    receiver_account_id bigint not null, sender_account_id bigint not null,
                    transaction_date timestamp(6) not null,
                    status varchar(255) not null check (status in ('SUCCESS','PENDING','FAILED')), primary key (id));
                alter table if exists accounts add constraint fk_acc_user foreign key (user_id) references users;
                alter table if exists transactions add constraint fk_tx_recv foreign key (receiver_account_id) references accounts;
                alter table if exists transactions add constraint fk_tx_send foreign key (sender_account_id) references accounts;
                """);
        jdbc.execute("""
                insert into users (first_name, last_name, tckn, email, password) values
                    ('Berk', 'Topal', '10000000146', 'berk@old.local', 'plaintext1'),
                    ('Ayşe', 'Kaya', '11111111110', 'ayse@old.local', 'plaintext2');
                insert into accounts (user_id, iban, balance, currency) values
                    (1, 'TR000000000000000000000001', 900.00, 'TL'),
                    (2, 'TR000000000000000000000002', -50.00, 'TRY');
                insert into transactions (sender_account_id, receiver_account_id, amount, transaction_date, status) values
                    (1, 2, 100.00, '2025-01-15 10:00:00', 'SUCCESS');
                """);
    }

    @Test
    void upgradesLegacySchemaPreservingData() {
        migrate();

        List<String> applied = jdbc.queryForList(
                "select version from flyway_schema_history where success order by installed_rank", String.class);
        assertThat(applied).containsExactly("0", "1", "2", "3");

        // Veriler korunur ve normalize edilir
        assertThat(jdbc.queryForObject("select currency from accounts where id = 1", String.class)).isEqualTo("TRY");
        assertThat(jdbc.queryForObject("select name from accounts where id = 1", String.class)).isEqualTo("Vadesiz Hesap");
        Map<String, Object> tx = jdbc.queryForMap("select reference, currency, category, transaction_date from transactions where id = 1");
        assertThat(tx.get("reference")).isEqualTo("BQ000000000001");
        assertThat(tx.get("currency")).isEqualTo("TRY");
        assertThat(tx.get("category")).isEqualTo("GENERAL");
        // Eski yerel saat (İstanbul, UTC+3) doğru ana dönüştürülür
        assertThat(((Timestamp) tx.get("transaction_date")).toInstant()).isEqualTo(Instant.parse("2025-01-15T07:00:00Z"));
        // Düz metin şifre ilk girişte yükseltileceği için olduğu gibi kalır
        assertThat(jdbc.queryForObject("select password from users where id = 1", String.class)).isEqualTo("plaintext1");
    }

    @Test
    void newConstraintsGuardFutureWritesButTolerateHistoricalBadRows() {
        migrate();

        // Geçmişteki negatif bakiye migration'ı bozmaz...
        assertThat(jdbc.queryForObject("select balance from accounts where id = 2", BigDecimal.class))
                .isEqualByComparingTo("-50.00");
        // ...ama yeni bir negatif bakiye yazılamaz
        assertThatThrownBy(() -> jdbc.update("update accounts set balance = -1 where id = 1"))
                .hasMessageContaining("chk_accounts_balance_non_negative");
        assertThatThrownBy(() -> jdbc.update("""
                insert into transactions (reference, sender_account_id, receiver_account_id, amount, currency, transaction_date, status)
                values ('BQX', 1, 2, -5, 'TRY', now(), 'SUCCESS')"""))
                .hasMessageContaining("chk_transactions_amount_positive");
    }

    @Test
    void migrationIsIdempotentOnSecondStartup() {
        migrate();
        migrate();
        assertThat(jdbc.queryForObject("select count(*) from flyway_schema_history", Integer.class)).isEqualTo(4);
    }

    private void migrate() {
        // application.properties ile aynı ayarlar
        Flyway.configure()
                .dataSource(dataSource)
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load()
                .migrate();
    }
}
