spring.application.name=p2p-transfer

# Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/p2p_db
spring.datasource.username=postgres

# Şifreyi sildik, ortam değişkenine bağladık
spring.datasource.password=${DB_PASSWORD}

# Hibernate Sihri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
